services:

  mongo-db:
    container_name: proyectoRuben-db_mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: /run/secrets/db_password
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - proyectoRuben-network
    secrets:
      - db_password

  nodejs:
    container_name: proyectoRuben-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      API_PORT: ${API_PORT}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - proyectoRuben-network


  nginx:
    container_name: proyectoRuben-nginx
    image: nginx:latest
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - nodejs
    networks:
      - proyectoRuben-network

networks:
  proyectoRuben-network:
    driver: bridge

secrets:
  db_password:
    file: db_password.txt