name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Bats
        run: |
          npm install -g bats
      - name: Check Bats version
        run: |
          bats --version
